-- Ejecutar en el SQL Editor de Supabase

create table reviews (
  id bigint generated by default as identity primary key,
  manga_title text not null,
  author text not null,
  content text not null,
  mood text,
  created_at timestamptz not null default now()
);
